// client/src/components/client/Contact.vue
<template>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>
            What the hell are you waiting for? <br>
            Say hello to me!
          </h1>
          <h4><a href="mailto:hello@echoestemplate.com">hello@echoestemplate.com</a></h4>
        </div>
      </div>
      <div class="row margin-top-45">
        <div class="col-md-12">
          <img class="img-responsive margin-top-45" src="img/5.jpg" alt="me">
        </div>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'Email',
  data () {
    return {
      dialog: false
    }
  }
}
</script>

<style scoped>

</style>

// client/src/app/client/contact/components/contact.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'client-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})
export class ContactComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div>
  <client-navigation></client-navigation>
  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>
            What the hell are you waiting for? <br>
            Say hello to me!
          </h1>
          <h4><a href="mailto:hello@echoestemplate.com">hello@echoestemplate.com</a></h4>
        </div>
      </div>
      <div class="row margin-top-45">
        <div class="col-md-12">
          <img class="img-responsive margin-top-45" src="img/5.jpg" alt="me">
        </div>
      </div>
    </div>
  </section>
</div>
