// client/src/app/client/home/components/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'client-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  constructor() {
  }

  ngOnInit() {
  }

}

<div>
  <client-navigation></client-navigation>
  <div class="span12">
    <div class="col-md-6 no-gutter text-center fill">
      <h2 class="vcenter">Simple is beautiful</h2>
    </div>
    <div class="col-md-6 no-gutter text-center">
      <div id="header" data-speed="2" data-type="background">
        <div id="headslide" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="img/4.jpg" alt="Slide">
            </div>
            <div class="item">
              <img src="img/3.jpg" alt="Slide">
            </div>
            <div class="item">
              <img src="img/1.jpg" alt="Slide">
            </div>
            <div class="item">
              <img src="img/2.jpg" alt="Slide">
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div style="clear:both;"></div>
</div>

// client/src/components/client/Home.vue
<template>
    <div class="span12">
        <div class="col-md-6 no-gutter text-center fill">
            <h2 class="vcenter">Simple is beautiful</h2>
        </div>
        <div class="col-md-6 no-gutter text-center">
            <div id="header" data-speed="2" data-type="background">
                <div id="headslide" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img src="img/4.jpg" alt="Slide">
                        </div>
                        <div class="item">
                            <img src="img/3.jpg" alt="Slide">
                        </div>
                        <div class="item">
                            <img src="img/1.jpg" alt="Slide">
                        </div>
                        <div class="item">
                            <img src="img/2.jpg" alt="Slide">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
  name: 'Home'
}
</script>

<style scoped>

</style>
