// client/src/components/client/About.vue
<template>
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>
                        Simplicity, purity, because
                        <br>
                        less is beautiful
                    </h1>
                    <br>
                    <img class="img-responsive margin-top-45" src="img/4.jpg" alt="me">
                </div>
            </div>
            <br>
            <div class="row margin-top-45">
                <div class="col-md-3">
                    <h2>My story</h2>
                </div>
                <div class="col-md-9">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula libero auctor dolor vulputate varius. Nunc ac nisl non felis finibus ultricies. Donec at porttitor lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin volutpat augue ex. In hac habitasse platea dictumst. Suspendisse at ante ligula. Nulla facilisis velit egestas massa imperdiet, id posuere turpis feugiat.
                    </p>
                    <br>
                    <p>
                        Etiam at consectetur sapien, vel laoreet diam. Aliquam erat volutpat. Quisque fermentum purus ac justo fermentum vulputate eu id libero. Donec quam ipsum, malesuada nec interdum in, commodo vel nisl. Aliquam erat volutpat. Donec suscipit molestie urna, at pharetra tortor interdum eget. Ut lobortis viverra ex, quis faucibus sapien iaculis in. Suspendisse laoreet ornare justo sit amet fermentum. Pellentesque non nulla id libero pretium bibendum vel nec dolor.
                    </p>
                </div>
            </div>
            <div class="row margin-top-45">
                <div class="col-md-3">
                    <h2>Services</h2>
                </div>
                <div class="col-md-9">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula libero auctor dolor vulputate varius. Nunc ac nisl non felis finibus ultricies. Donec at porttitor lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin volutpat augue ex. In hac habitasse platea dictumst. Suspendisse at ante ligula. Nulla facilisis velit egestas massa imperdiet, id posuere turpis feugiat.
                    </p>
                </div>
            </div>
            <div class="row margin-top-45">
                <div class="col-md-3">
                    <h2>Clients</h2>
                </div>
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-4">
                            <ul class="list-unstyled">
                                <li>Bugatti</li>
                                <li>Vogue</li>
                                <li>Class</li>
                                <li>Hollister</li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul class="list-unstyled">
                                <li>Zara</li>
                                <li>Coca Cola</li>
                                <li>Ferrari</li>
                                <li>Mercedes Benz</li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <ul class="list-unstyled">
                                <li>Tiger</li>
                                <li>Capcom</li>
                                <li>Zara Home</li>
                                <li>Martini</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</template>

<script>
export default {
  name: 'About'
}
</script>

<style scoped>

</style>

// client/src/app/client/about/components/about.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'client-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.css']
})
export class AboutComponent implements OnInit {

  ngOnInit() {
  }

}

<div>
  <client-navigation></client-navigation>
  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>
            Simplicity, purity, because
            <br>
            less is beautiful
          </h1>
          <br>
          <img class="img-responsive margin-top-45" src="img/4.jpg" alt="me">
        </div>
      </div>
      <br>
      <div class="row margin-top-45">
        <div class="col-md-3">
          <h2>My story</h2>
        </div>
        <div class="col-md-9">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula libero auctor dolor vulputate
            varius.
            Nunc ac nisl non felis finibus ultricies. Donec at porttitor lorem. Vestibulum ante ipsum primis in faucibus
            orci luctus et ultrices posuere cubilia Curae; Proin volutpat augue ex. In hac habitasse platea dictumst.
            Suspendisse at ante ligula. Nulla facilisis velit egestas massa imperdiet, id posuere turpis feugiat.
          </p>
          <br>
          <p>
            Etiam at consectetur sapien, vel laoreet diam. Aliquam erat volutpat. Quisque fermentum purus ac justo
            fermentum vulputate eu id libero. Donec quam ipsum, malesuada nec interdum in, commodo vel nisl. Aliquam
            erat
            volutpat. Donec suscipit molestie urna, at pharetra tortor interdum eget. Ut lobortis viverra ex, quis
            faucibus sapien iaculis in. Suspendisse laoreet ornare justo sit amet fermentum. Pellentesque non nulla id
            libero pretium bibendum vel nec dolor.
          </p>
        </div>
      </div>
      <div class="row margin-top-45">
        <div class="col-md-3">
          <h2>Services</h2>
        </div>
        <div class="col-md-9">
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula libero auctor dolor vulputate
            varius.
            Nunc ac nisl non felis finibus ultricies. Donec at porttitor lorem. Vestibulum ante ipsum primis in faucibus
            orci luctus et ultrices posuere cubilia Curae; Proin volutpat augue ex. In hac habitasse platea dictumst.
            Suspendisse at ante ligula. Nulla facilisis velit egestas massa imperdiet, id posuere turpis feugiat.
          </p>
        </div>
      </div>
      <div class="row margin-top-45">
        <div class="col-md-3">
          <h2>Clients</h2>
        </div>
        <div class="col-md-9">
          <div class="row">
            <div class="col-md-4">
              <ul class="list-unstyled">
                <li>Bugatti</li>
                <li>Vogue</li>
                <li>Class</li>
                <li>Hollister</li>
              </ul>
            </div>
            <div class="col-md-4">
              <ul class="list-unstyled">
                <li>Zara</li>
                <li>Coca Cola</li>
                <li>Ferrari</li>
                <li>Mercedes Benz</li>
              </ul>
            </div>
            <div class="col-md-4">
              <ul class="list-unstyled">
                <li>Tiger</li>
                <li>Capcom</li>
                <li>Zara Home</li>
                <li>Martini</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
